name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: stable
        run: cargo test
      - name: msrv
        shell: bash
        run: |
          msrv=$(cat Cargo.toml | grep "rust-version" | sed 's/.*"\(.*\)".*/\1/')
          rustup default $msrv
          cargo test
      - name: clippy
        run: |
          rustup component add clippy
          cargo clippy --all-targets
